version: "2"
services:
  api:
    build: ./Dockerfile
    links:
      - db
    ports:
      - "5000:5000"


  sum2:
      build: ./task_runners/services/sum2_service
      links:
        - db
      ports:
        - "5001:5001"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro