FROM python:3.9

EXPOSE 5000

WORKDIR /home/tasker

COPY secret secret
COPY api api
COPY common common

ENV PYTHONPATH=":common:api"

RUN pip3 install -r api/requirements.txt && pip3 install -r common/requirements.txt

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

CMD python3 api/tasker_api.py
