FROM python:3.9

EXPOSE 5002

WORKDIR /home/tasker

COPY secret secret
COPY task_runners task_runners
COPY common common

ENV PYTHONPATH=":common:task_runners"

RUN pip3 install -r task_runners/requirements.txt && pip3 install -r common/requirements.txt

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

CMD python3 task_runners/services/mult3_service/start.py
