FROM python:3.9
ENV SERVICE_DIR=mult3_service
EXPOSE 5002

WORKDIR /home/tasker
RUN mkdir -p src/task_runners/
COPY ../secret secret
COPY ../src/common src/common
COPY ../src/task_runners/*.py src/task_runners/

ENV PYTHONPATH=":src"

RUN pip3 install -r src/common/requirements.txt
COPY ../src/task_runners/$SERVICE_DIR src/task_runners/$SERVICE_DIR

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

CMD python3 src/task_runners/$SERVICE_DIR/start.py
